### ISSUE TITLE
Implement path for setting table width (prawn-table's width options)

### ISSUE THREAD

**Issue by allthesignals** [puzzle/prawn-markup#32]
According to [prawn-table](https://prawnpdf.org/prawn-table-manual.pdf), there's a width option:

> The default table width depends on the content provided. It will expand up to the current bounding box width to fit the content. If you want the table to have a fixed width no matter the content you may use the :width option to manually set the width.

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/5004319/157791195-a98aba93-e91f-4fe0-86ec-833f407256e9.png">

I can't find a way to do this. Maybe we should start with getting it to honor the table options:

```ruby
pdf.markup_options = {
  table: { width: 320 }
}
```

Maybe in the future, it could work this way:

```html
<table style="width: 320px;">
</table>
```

Thoughts?

**Comment by codez** [comment]
Tables, like all other components, are always set to full width. As we do interpret the width style for table cells, I think it would be possible for tables, too. 

However, I am a bit reluctant to add this because basically, CSS is out of scope for this gem. Do you have a good use case that supports this feature?

**Comment by codez** [comment]
Closed because of inactivity
