### ISSUE TITLE
Bug with consecutive line break tags (<br/>) between different tags

### ISSUE THREAD

**Issue by allthesignals** [puzzle/prawn-markup#33]
This markup behaves unexpectedly:

```html
<i>hello</i><br/><br/><br/><p>world</p>
```

Producing:

> _hello_
> _world_

I was expecting it to produce:

> _hello_
>
>
> _world_

Happy to take a look but want to confirm that this is actually a bug and that I'm not misinterpreting something :)

**Comment by allthesignals** [comment]
It seems like the presence of any block tags (paragraph `<p>`, division `div`) short-circuits the effect of any neighboring line break `<br/>` tags:

`<p>hello</p><br/><br/><br/><br/><br/><br/><br/><b>world</b>`

<img width="315" alt="image" src="https://user-images.githubusercontent.com/5004319/157990395-3c8eb5be-31f6-441d-a2d7-c2dc4fd4568a.png">

Regular text tags seem to be fine:

`<i>hello</i><br/><br/><br/><br/><br/><br/><br/><b>world</b>`

<img width="495" alt="image" src="https://user-images.githubusercontent.com/5004319/157990763-f3811bb2-ac72-4ed9-b32a-299b37cfd261.png">

**Comment by allthesignals** [comment]
@codez yup, more than happy to take a look! It might be a while.

> I guess this comes from the use-case when there is only one <br/> before or after a <p>. In this case, it is desired that the br is ignored. So n-1 br could be kept.

This makes sense. I'll try to update the test to reflect this more exactly...

**Comment by goulvench** [comment]
I'm having the same issue when rendering Trix-generated HTML, and switching from `<div>`s to `<p>'s isn't an option because `<ul>` and `<ol>` are not allowed inside paragraphs. 

I tried replacing `<br><br>` with `<br>\n<br>`, `<br>&nbsp;<br>` but the normalizer very efficiently discards every variation I could think of. 

What worked was replacing `"<br><br>"` with `"</div><p><br></p><div>"` or simply `"<p><br></p>"` before feeding HTML to prawn-markup, but this workaround will break if my input starts containing paragraphs. 

I'd be happy to contribute a PR for this issue but I'm not sure where to start, and I'm quite busy at the moment anyway.

**Comment by codez** [comment]
I think the stripping happens here: https://github.com/puzzle/prawn-markup/blob/3a1b39bff018395c825456fe40d92c57e67601eb/lib/prawn/markup/processor/blocks.rb#L78
If there are just newlines, https://github.com/puzzle/prawn-markup/blob/3a1b39bff018395c825456fe40d92c57e67601eb/lib/prawn/markup/processor.rb#L96 might play a role as well.

**Comment by codez** [comment]
Closed because of inactivity
